package com.my.line_bot_dynamo.models;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "MessageTable")
public class messageObject{
    private String id;

    @NotEmpty
    private String message;

    public messageObject() {
    }

    public messageObject(String message) {
        //this.id = id;
        this.message = message;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getid(){
        return id;
    }

    public void setid(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "message")
    public String getMessage(){
        return message;
    }

    public void setMessage(String message){
        this.message = message;
    }
}