package com.my.line_bot_dynamo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "ParseInfoTable")
public class ParseInfo{
    private String id;
    private String url;
    private String content;

    public ParseInfo(){

    }

    public ParseInfo(String url, String content){
        this.url = url;
        this.content = content;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getid(){
        return id;
    }

    public void setid(String id){
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "url")
    public String getUrl(){
        return url;
    }

    public void setUrl(String url){
        this.url = url;
    }

    @DynamoDBAttribute(attributeName = "content")
    public String getContent(){
        return content;
    }

    public void setContent(String content){
        this.content = content;
    }
}